spring:
    datasource:
        url: jdbc:mariadb://localhost:3306/vollmed
        username: root
        password: 135790
    jpa:
        show-sql: true
        properties:
            hibernate:
                format_sql: true

server:
    error:
        include-stacktrace: never

api:
    security:
        secret: ${JWT_SECRET:12345678}