CREATE TABLE consultas (
	ID BIGINT auto_increment NOT NULL,
    MEDICO_ID BIGINT NOT NULL,
    PACIENTE_ID BIGINT NOT NULL,
    DATA_CONSULTA DATETIME NOT NULL,
    CONSTRAINT consultas_PK PRIMARY KEY (ID),
    CONSTRAINT MEDICO_CONSULTA_FK FOREIGN KEY (MEDICO_ID) REFERENCES medicos(ID),
    CONSTRAINT PACIENTE_CONSULTA_FK FOREIGN KEY (PACIENTE_ID) REFERENCES pacientes(ID)
);